-- Expedite-profile-review feature: tracks each payment attempt (order_id,
-- pre-payment) and marks it paid (paid_at) once NicePay confirms it. One
-- row per attempt, updated in place — no separate "successful_X" table
-- needed since there's no limited-slot availability check like premium
-- listing has.
create table if not exists expedite_requests (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  payment_id text,
  teacher_id integer not null,
  amount integer not null,
  requested_at timestamptz not null default now(),
  paid_at timestamptz
);
